import type { Einstellungen } from './types';

// Standardwerte für eine neue Installation (Beispiel-Praxisdaten, frei änderbar unter "Stammdaten")
export const defaultEinstellungen: Einstellungen = {
  id: 'main',
  name: 'Anna Beispiel',
  berufsbezeichnung: 'Rehabilitationslehrerin für Orientierung und Mobilität',
  praxisname: 'Mobi – Praxis für Orientierung & Mobilität',
  adresse: { strasse: 'Beispielstraße 12', plz: '24103', ort: 'Kiel' },
  telefon: '0431 000000',
  email: 'kontakt@example.org',
  ik: '599999999',
  steuernummer: '19/000/00000',
  ustHinweis: 'Umsatzsteuerfrei gemäß § 4 Nr. 14 UStG.',
  kontoinhaber: 'Anna Beispiel',
  iban: 'DE89370400440532013000',
  bic: 'COBADEFFXXX',
  bank: 'Beispielbank',
  leistungen: [
    {
      id: 'l-om',
      bezeichnung: 'Training Orientierung & Mobilität (Einzelunterricht, 60 Min.)',
      positionsnummer: 'OM-01',
      einheit: 'UE',
      preis: 75,
      typ: 'einheit',
      leistungsart: 'O&M',
    },
    {
      id: 'l-lpf',
      bezeichnung: 'Training Lebenspraktische Fähigkeiten (Einzelunterricht, 60 Min.)',
      positionsnummer: 'LPF-01',
      einheit: 'UE',
      preis: 72,
      typ: 'einheit',
      leistungsart: 'LPF',
    },
    {
      id: 'l-erst',
      bezeichnung: 'Erstgespräch, Bedarfsermittlung und Trainingsplanung',
      positionsnummer: 'OM-00',
      einheit: 'pausch.',
      preis: 90,
      typ: 'pauschal',
      zeitpunkt: 'beginn',
      leistungsart: 'O&M',
    },
    {
      id: 'l-bericht',
      bezeichnung: 'Abschlussbericht an Kostenträger / Arzt',
      positionsnummer: 'OM-99',
      einheit: 'pausch.',
      preis: 45,
      typ: 'pauschal',
      zeitpunkt: 'ende',
      leistungsart: 'O&M',
    },
    {
      id: 'l-km',
      bezeichnung: 'Fahrtkosten Hausbesuch',
      positionsnummer: 'FK-01',
      einheit: 'km',
      preis: 0.3,
      typ: 'km',
      leistungsart: 'Sonstige',
    },
  ],
  kmPauschale: 0.3,
  standardDauerMin: 60,
  zahlungszielTage: 30,
  kvWiedervorlageTage: 14,
  verordnungGueltigTage: 28,
  rechnungPraefix: 'RE-',
  naechsteRechnungsnummer: 1,
  kvPraefix: 'KV-',
  naechsteKvNummer: 1,
  rezeptPraefix: 'VO-',
  naechsteRezeptNummer: 1,
  zuzahlungAktiv: false,
  autoSperreMin: 5,
  theme: 'auto',
};
